LimeChain/hedera-mirror-node

docs/configuration.md, hedera-mirror-rosetta/app/services/network_service.go, hedera-mirror-rosetta/cmd/main.go, hedera-mirror-rosetta/config/application.yml, hedera-mirror-rosetta/types/config.go
Implements `/network/list` from Rosetta API
Fixes #27 
**Checklist**
=> Feature: /network/list

hedera-mirror-rosetta/app/domain/repositories/block.go, hedera-mirror-rosetta/app/domain/repositories/transaction.go, hedera-mirror-rosetta/app/errors/errors.go, hedera-mirror-rosetta/app/persistance/postgres/block/block.go, hedera-mirror-rosetta/app/persistance/postgres/transaction/transaction.go, hedera-mirror-rosetta/app/services/block_service.go
Add custom error handling, based on Rosetta API docs
**Checklist**
=> Feature(hedera-mirror-rosetta): Error handling

hedera-mirror-rosetta/app/domain/services/entity-id-codec.go, hedera-mirror-rosetta/app/domain/services/entity-id-codec_test.go, hedera-mirror-rosetta/app/domain/types/account.go, hedera-mirror-rosetta/app/domain/types/block.go, hedera-mirror-rosetta/app/domain/types/operation.go, hedera-mirror-rosetta/app/domain/types/transaction.go, hedera-mirror-rosetta/app/errors/errors.go, hedera-mirror-rosetta/app/persistance/postgres/transaction/transaction.go, hedera-mirror-rosetta/app/services/block_service.go
**Detailed Description**:
- Implements `AccountID Codec` (as per the `EntityIdEndec.java` implementation)
- Adds unit tests for the codec
- Adds new Domain Type - `Account`
- Implements `FromRosettaOperation` function
- TODOs for the `ToRosettaOperation` function are completed
- Refactored the `constructID` function 
Fixes #33
Fixes #36
Fixes #65 
**Special notes for your reviewer**:
**Checklist**
=> Full implementation of block API call

docs/configuration.md, hedera-mirror-rosetta/app/domain/repositories/block.go, hedera-mirror-rosetta/app/domain/repositories/transaction.go, hedera-mirror-rosetta/app/persistance/postgres/block/block.go, hedera-mirror-rosetta/app/persistance/postgres/transaction/transaction.go, hedera-mirror-rosetta/app/services/block_service.go, hedera-mirror-rosetta/app/services/network_service.go, hedera-mirror-rosetta/cmd/main.go, hedera-mirror-rosetta/config/application.yml, hedera-mirror-rosetta/tools/hex/hex.go, hedera-mirror-rosetta/tools/maphelper/maphelper.go, hedera-mirror-rosetta/types/config.go
Partial implementation of '/network/options' & '/network/status'
Fixes #28 
Fixes #29 
**Special notes for your reviewer**:
Purposely have not added `nodeVersion` and `version` in `configuration.md`, due to lack of information about these configurations.
**Checklist**
=> [WIP] Feature(hedera-mirror-rosetta): '/network/options' & '/network/status'

hedera-mirror-rosetta/app/services/construction_service.go
=> Fix(hedera-mirror-rosetta): Construction API '/payloads' -> return tx body as payload to be signed

.github/workflows/rosetta-validation.yml
Switch Rosetta validation trigger from `push` to `pull_request`.
=> Ci(hedera-mirror-rosetta): Switch Rosetta validation trigger

docs/configuration.md, hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/controller/ConsensusController.java, hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/ListenerProperties.java, hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/NotifyingTopicListener.java, hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/SharedPollingTopicListener.java, hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/controller/ConsensusControllerTest.java, hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/client/TopicMessagePublishClient.java, hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/handler/SDKClientHandler.java, hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/props/NodeInfo.java, hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/HCSDirectStubTopicSampler.java, hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/HCSMAPITopicSampler.java, hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/TopicMessagesPublishSampler.java, hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/result/HCSSamplerResult.java, hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/listener/AbstractSharedTopicListenerTest.java, hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/listener/AbstractTopicListenerTest.java, hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/listener/NotifyingTopicListenerTest.java, hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/listener/SharedPollingTopicListenerTest.java, hedera-mirror-test/pom.xml, pom.xml
**Special notes for your reviewer**:
**Checklist**
=> Apply latest origin master commits

docs/configuration.md, hedera-mirror-rosetta/app/services/construction_service.go, hedera-mirror-rosetta/app/services/network_service.go, hedera-mirror-rosetta/cmd/main.go, hedera-mirror-rosetta/config/application.yml, hedera-mirror-rosetta/config/config.go, hedera-mirror-rosetta/tools/validator/validator.go
feat: remove `CryptoCreateAccount` operation type handle
docs: add missing config params
docs: add inline documentation
refactor: remove unused variables, functions
=> Feature(hedera-mirror-rosetta): Remove CryptoCreateAccount handle

Dockerfile, docs/configuration.md, supervisord.conf
=> Infrastructure(docker): Use only one volume for persistent data

docs/configuration.md, hedera-mirror-rosetta/cmd/config.go, hedera-mirror-rosetta/cmd/main.go, hedera-mirror-rosetta/config/application.yml, hedera-mirror-rosetta/config/config.go, hedera-mirror-rosetta/go.mod, hedera-mirror-rosetta/go.sum, hedera-mirror-rosetta/types/config.go
After parsing .yaml configuration, read all env variables for confg struct
Add `online` property -> whether to run app in online/offline mode
Update docs
Fixes #56 
**Checklist**
=> Feature(hedera-mirror-rosetta): run in online/offline mode + read .env

Dockerfile, run_supervisord.sh, supervisord-offline.conf
Fixes #100 
Related to #86 
**Checklist**
=> Infrastructure(docker): pass env variables, add online/offline mode, init db script

hedera-mirror-rosetta/app/domain/types/account.go, hedera-mirror-rosetta/app/domain/types/address_book_entry.go, hedera-mirror-rosetta/app/domain/types/amount.go, hedera-mirror-rosetta/app/services/construction_service.go, hedera-mirror-rosetta/tools/parse/parse.go, hedera-mirror-rosetta/tools/validator/validator.go
* `strconv.Atoi` -> `strconv.ParseInt`
* `FormatToString` -> `String`
Fixes #None
**Checklist**
=> Refactor(hedera-mirror-rosetta): Int64 parses

hedera-mirror-rosetta/app/domain/repositories/transaction.go, hedera-mirror-rosetta/app/errors/errors.go, hedera-mirror-rosetta/app/persistence/postgres/transaction/transaction.go, hedera-mirror-rosetta/app/services/network_service.go
* Return errors if no operation statuses or types are found
* Memory cache statuses & types
Fixes #83 
**Checklist**
=> Feature(hedera-mirror-rosetta): cache operation types & statuses

hedera-mirror-rosetta/app/persistence/postgres/addressbook/entry/entry.go
=> Fix(hedera-mirror-rosetta): Update peers retrieval

docs/installation.md, hedera-mirror-rosetta/validation/run-validation.sh
=> Docs(hedera-mirror-rosetta): Add guide to run api & rosetta-cli validation locally

hedera-mirror-rosetta/validation/testnet/validate-from-genesis.json
Signed-off-by: Daniel Ivanov <daniel.k.ivanov95@gmail.com>
Fixes the configuration of the Rosetta Tesnet Validation
**Checklist**
=> Bug: Fix Rosetta Testnet validation config

hedera-mirror-rosetta/app/persistence/account/account.go, hedera-mirror-rosetta/app/persistence/transaction/transaction.go
=> Fix(hedera-mirror-rosetta): escape sql where statement

hedera-mirror-rosetta/build/Dockerfile, hedera-mirror-rosetta/build/run_supervisord.sh
=> Fix(hedera-mirror-rosetta): All-in-one Docker config - remove yq, disable redis

docs/installation.md
Fixes #None
**Special notes for your reviewer**:
**Checklist**
=> Docs(hedera-mirror-rosetta): All-in-one Dockerfile

docs/installation.md
Command how to run locally unit tests
Closes #130 
**Checklist**
=> Docs(hedera-mirror-rosetta): Run unit tests

hedera-mirror-rosetta/app/domain/types/account_test.go, hedera-mirror-rosetta/app/domain/types/address_book_entry_test.go, hedera-mirror-rosetta/app/domain/types/block_test.go, hedera-mirror-rosetta/tools/hex/hex_test.go, hedera-mirror-rosetta/tools/maphelper/maphelper_test.go, hedera-mirror-rosetta/tools/validator/validator_test.go
**Changes**
PR comments resolution for types and tools folders
=> PR Comments resolution
